refactor(Image): from JS to TS and add tests
softconstruct/gene-ui-components pull request #102
Opened 2024-03-14 07:18 UTC by NarekArshakyan

2024-03-26 13:24 UTC, GaroGabrielyan requested changes

2024-03-26 13:24 UTC, GaroGabrielyan commented on src/lib/atoms/Image/Image.stories.tsx
>      argTypes: {
Change all `category: category....` to `...propCategory.`

2024-03-26 13:24 UTC, GaroGabrielyan commented on src/lib/atoms/Image/Image.stories.tsx
>  Default.args = {
Please check all default props and don't repeat.

2024-03-26 13:24 UTC, GaroGabrielyan commented on src/lib/atoms/Image/Image.tsx
> +     * Addional className
Typo: In word 'Addional'

2024-03-26 13:24 UTC, GaroGabrielyan commented on src/lib/atoms/Image/Image.tsx
>      const isValidSource = useMemo(() => typeof src === 'string' && src !== '', [src]);
```suggestion
    const isValidSource = useMemo(() => typeof src === 'string' && src.length, [src]);
```

2024-03-26 13:24 UTC, GaroGabrielyan commented on src/lib/atoms/Image/Image.tsx
> +const Image: FC<Partial<IImageProps>> = ({
Please remove Partial and in storybook Image Docs you can see all types descriptions.
```suggestion
const Image: FC<IImageProps> = ({
```

2024-03-27 13:32 UTC, NarekArshakyan commented on src/lib/atoms/Image/Image.tsx
>      const isValidSource = useMemo(() => typeof src === 'string' && src !== '', [src]);
these are the same expression

2024-03-28 09:04 UTC, GaroGabrielyan approved these changes

2024-04-19 08:29 UTC, NairaMisakyan commented on src/lib/atoms/Image/Image.test.tsx
> +        const className = 'test';
className is declared but its value is never read

2024-04-24 21:28 UTC, merged