feat(Pill): new component
softconstruct/gene-ui-components pull request #144
Opened 2024-07-18 13:03 UTC by GaroGabrielyan

2024-08-07 11:19 UTC, NairaMisakyan submitted a review, later dismissed

2024-08-28 15:57 UTC, AregSoft approved these changes

2024-09-30 07:52 UTC, hamikhambardzumyan requested changes

2024-09-30 10:39 UTC, hamikhambardzumyan requested changes

2024-09-30 10:39 UTC, hamikhambardzumyan commented on src/lib/atoms/Pill/Pill.tsx
> +                    <span ref={textRef} className="pill__text ellipsis-text">
One more thing, why does `ellipsis-text` permanently exist on the `span` I guess it should be a conditional class and applied to the `span` when it has truncation 🤔

2024-10-03 12:48 UTC, hamikhambardzumyan approved these changes

2024-10-03 12:49 UTC, merged