feat(Avatar): new component
softconstruct/gene-ui-components pull request #146
Opened 2024-07-18 13:06 UTC by GaroGabrielyan

2024-08-09 09:51 UTC, GaroGabrielyan commented on src/lib/atoms/Avatar/Avatar.tsx
>          <div
This is an interactive element and i think that enter must work on it as onClick

2024-08-12 10:23 UTC, NarekArshakyan commented on src/lib/atoms/Avatar/Avatar.stories.tsx
> +        src: args({ control: 'text', ...propCategory.functionality }),
why ?

2024-09-03 10:21 UTC, AregSoft approved these changes

2024-10-01 10:15 UTC, hamikhambardzumyan requested changes

2024-10-01 10:15 UTC, hamikhambardzumyan commented on src/lib/atoms/Avatar/Avatar.tsx
> +            {src && <img className="avatar__image" alt={'avatar'} src={src} />}
Here is exist issue in rendering `src` and `icon` will be rendered together handle logic

2024-10-01 10:15 UTC, hamikhambardzumyan commented on src/lib/atoms/Avatar/Avatar.test.tsx
> +        console.log(setup.debug(), 88888);
Remove the log

2024-10-01 10:15 UTC, hamikhambardzumyan commented on src/lib/atoms/Avatar/Avatar.test.tsx
> +    it('renders onClick prop correctly', () => {
Follow the test writing guideline

2024-10-01 14:57 UTC, hamikhambardzumyan requested changes

2024-10-01 14:57 UTC, hamikhambardzumyan commented on src/lib/atoms/Avatar/Avatar.test.tsx
> +import { Square } from '@geneui/icons';
```suggestion
import { Square } from '@geneui/icons'; // TODO: replace with the person icon
```

2024-10-01 15:08 UTC, hamikhambardzumyan approved these changes

2024-10-01 15:09 UTC, merged