Fix (ExtendedInput): remove space in the beginning of ExtendedInput placeholder
softconstruct/gene-ui-components pull request #20
Opened 2023-11-22 10:24 UTC by AregSoft

[Issue link](https://github.com/softconstruct/gene-ui-components/issues/18)

2023-11-23 07:10 UTC, GaroGabrielyan approved these changes

2023-11-24 09:05 UTC, hamikhambardzumyan requested changes

2023-11-24 09:05 UTC, hamikhambardzumyan commented on package-lock.json
Why do you have a change in this file?

2023-11-24 09:05 UTC, hamikhambardzumyan commented on package.json
> +        "@geneui/components": "^2.11.1",
Why do you add the dependency `@geneui/components`?

2023-11-24 10:43 UTC, hamikhambardzumyan approved these changes

2023-11-24 10:44 UTC, merged