Fix (MapChart): remove animation of MapChart
softconstruct/gene-ui-components pull request #21
Opened 2023-11-22 10:59 UTC by AregSoft

[Issue link](https://github.com/softconstruct/gene-ui-components/issues/17)

2023-11-23 07:06 UTC, GaroGabrielyan submitted a review, later dismissed

2023-11-24 09:00 UTC, hamikhambardzumyan requested changes

2023-11-24 09:00 UTC, hamikhambardzumyan commented on src/lib/molecules/Charts/MapChart/index.js
> +                animation: false
The change will affect all animations in the Map Chart component, but the issue is only for blinking animation when the data prop is changed. e.g. this change will remove zoom in/out animation too.

2023-11-24 11:08 UTC, hamikhambardzumyan commented
@AregSoft look at [this option](https://api.highcharts.com/highcharts/plotOptions.series.animation) from `highcharts` API documentation. Seems it resolves your case.

2023-11-25 14:08 UTC, merged