feat(SegmentedControl): new component
softconstruct/gene-ui-components pull request #223
Opened 2024-12-09 09:42 UTC by NarekArshakyan

### Chromatic Build Summary 
**Build URL:** https://www.chromatic.com/build?appId=66daee7859a843dd87bfb3d7&number=875 
**Storybook URL:** https://66daee7859a843dd87bfb3d7-rdfityfbrx.chromatic.com/

2024-12-17 13:51 UTC, hamikhambardzumyan requested changes

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +interface ISegmentedControlProps extends Omit<IGlobalProps, "name" | "children" | "isSelected"> {
Here you don't need to extend another interface.

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +import { IGlobalProps } from "./types";
```suggestion
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +     * Control component. Renders inside the component
```suggestion
     * SegmentedControlItem component. Renders inside the component
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +     * Works when the user clicks on one of the buttons. Returns the value that was written as a name in the Control component.
```suggestion
     * It works when the user clicks on one of the control items. Returns the value of the `name` prop from the `SegmentedControlItem`
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +    Icon?: FC<IconProps>;
```suggestion
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +
```suggestion
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +     * Indicates whether the `button` is `disabled`, preventing user interaction, focus, click etc...
```suggestion
     * Indicates whether the `SegmentedControlItem` is `disabled`, preventing user interaction, focus, click etc...
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +    infoText?: string;
Move near to the `label` prop.

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +            <Label labelText={label} required size={textSizes} infoText={infoText} />
Why is this always `required`? Add prop for required.

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +    const textSizes = props.size === "large" ? "medium" : props.size;
Memoize this variable. 
Use destructuring to take the `size` prop

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +    };
```suggestion
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +    };
```suggestion
  const clickHandler = (name: string) => {
        setSelectedElementName(name);
    };
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +
useEffect(() => {
        onChange(selectedElementName);
    }, [selectedElementName]);

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +                        isSelected: selectedElementName ? selectedElementName === el.props.name : el.props.isSelected
```suggestion
                        selected: selectedElementName ? selectedElementName === el.props.name : el.props.selected,
                        onSelect: clickHandler
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +                        ...props,
Remove the `...props` and pass only props that need for the `SegmentedControlItem`.

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +                onKeyDown={onKeyDown}
```suggestion
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +                tabIndex={-1}
```suggestion
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/SegmentedControl.tsx
> +                role="button"
```suggestion
```

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/Control.tsx
> +const Control: FC<IGlobalProps> = ({ children, name, Icon, size = "medium", disabled = false, isSelected = false }) => {
Take the `onSelect` from props.

2024-12-17 13:51 UTC, hamikhambardzumyan commented on src/components/atoms/SegmentedControl/Control.tsx
> +            name={name}
Add click handler here.
```
onClick={() => onSelect(name)}
```

2025-11-03 08:12 UTC, AregSoft submitted a review, later dismissed

2025-11-04 14:31 UTC, merged