fix(Widget): add new prop to extend the headerActions prop functional in compact type
softconstruct/gene-ui-components pull request #57
Opened 2024-01-29 07:51 UTC by hamikhambardzumyan

2024-01-31 10:40 UTC, NairaMisakyan submitted a review, later dismissed

2024-01-31 10:56 UTC, GaroGabrielyan commented on stories/molecules/Widget/Widget.stories.jsx
> +        withHeaderActions: args({ control: 'boolean', ...appearance }),
By adding the `withHeaderActions` prop, we adding additional functionality so please remove this prop from appearance to functionality group.

2024-01-31 14:14 UTC, GaroGabrielyan requested changes

2024-01-31 14:27 UTC, GaroGabrielyan requested changes

2024-01-31 14:27 UTC, GaroGabrielyan commented on src/lib/molecules/Widget/index.js
> +                    {img && <li className="image">{img && <img src={img} alt="" />}</li>}
Please remove redundant second `img` check.
```suggestion
                    {img && <li className="image"><img src={img} alt="" /></li>}
```

2024-01-31 14:27 UTC, GaroGabrielyan commented on src/lib/molecules/Widget/index.scss
> +            @include rtl(padding, 0 rem(20), 0 rem(20));
We can change this line with:
```suggestion
         padding-inline: rem(20);
```

2024-01-31 14:35 UTC, GaroGabrielyan submitted a review, later dismissed

2024-02-01 07:16 UTC, NairaMisakyan requested changes
If the widget size value is big and the img prop is present, the image aligns with the border.
![image (13)](https://github.com/softconstruct/gene-ui-components/assets/150226302/11cf1aee-96be-4f37-940a-1a2b39315682)

2024-02-01 09:21 UTC, NairaMisakyan approved these changes

2024-02-01 11:07 UTC, merged