fix(ValidatableNumberInput): clear bad values of input
softconstruct/gene-ui-components pull request #59
Opened 2024-01-31 13:51 UTC by AregSoft

2024-01-31 14:38 UTC, hamikhambardzumyan requested changes

2024-01-31 14:38 UTC, hamikhambardzumyan commented on src/lib/molecules/ValidatableElements/Elements/ValidatableNumberInput.js
> +            if (validity.badInput && !value.length) {
The bellow suggestion will cover also `x.` values case
 
```suggestion
            if ((validity.badInput && !value.length) || value.endsWith('.')) {
```

2024-02-01 06:29 UTC, NairaMisakyan approved these changes

2024-02-01 06:35 UTC, hamikhambardzumyan commented on src/lib/molecules/ValidatableElements/Elements/ValidatableNumberInput.js
> +            if (validity.badInput && !value.length) {
A value "x." in the context of a number input typically represents the number x as a floating-point number. The trailing dot suggests that it's a decimal value, even though there are no digits after the decimal point.

In JavaScript programming language, the dot (.) is used to indicate a decimal point. So, "1." is interpreted as the number 1.0 or simply 1.

Let's keep your change like exists.

2024-02-01 06:36 UTC, hamikhambardzumyan approved these changes

2024-02-01 10:57 UTC, merged