fix(DatePickerInput): disabled state of years in case if they is limit
softconstruct/gene-ui-components pull request #74
Opened 2024-02-14 07:36 UTC by AregSoft

2024-02-14 09:17 UTC, NairaMisakyan approved these changes

2024-02-21 09:05 UTC, GaroGabrielyan commented on src/lib/organisms/DatePicker/Years/index.js
> +            return true;
You can simplify here 
           ```
 if (!year) return false;
            if (min && !max)  return year >= dayjs(min).year();
            if (!min && max)  return year <= dayjs(max).year();
            if (min && max) return max && year <= dayjs(max).year() && min && year >= dayjs(min).year();
            return true;
```

2024-02-22 09:31 UTC, NairaMisakyan approved these changes

2024-02-23 07:18 UTC, GaroGabrielyan submitted a review, later dismissed

2024-02-23 13:59 UTC, hamikhambardzumyan requested changes

2024-02-23 13:59 UTC, hamikhambardzumyan commented on src/lib/organisms/DatePicker/Years/index.js
> +    const isYearMaxOrMinChecker = useCallback(
Rename the function e.g. `checkYearDisableState`

2024-02-23 13:59 UTC, hamikhambardzumyan commented on src/lib/organisms/DatePicker/Calendar/index.js
> +                dayjs(min).isSameOrBefore(dayjs(new Date()), 'date') &&
```suggestion
                dayjs(min).isSameOrBefore(dayjs(), 'date') &&
```

2024-02-23 13:59 UTC, hamikhambardzumyan commented on src/lib/organisms/DatePicker/Calendar/index.js
> +                    dayjs(max).isSameOrAfter(dayjs(new Date()), 'date')
```suggestion
                    dayjs(max).isSameOrAfter(dayjs(), 'date')
```

2024-02-23 13:59 UTC, hamikhambardzumyan commented on src/lib/organisms/DatePicker/Calendar/index.js
> +        if (min && !max) setIsThisDateAllowed(dayjs(min).isSameOrBefore(dayjs(new Date()), 'date'));
```suggestion
        if (min && !max) setIsThisDateAllowed(dayjs(min).isSameOrBefore(dayjs(), 'date'));
```

2024-02-23 13:59 UTC, hamikhambardzumyan commented on src/lib/organisms/DatePicker/Calendar/index.js
> +        if (!min && max) setIsThisDateAllowed(dayjs(max).isSameOrAfter(dayjs(new Date()), 'date'));
```suggestion
        if (!min && max) setIsThisDateAllowed(dayjs(max).isSameOrAfter(dayjs(), 'date'));
```

2024-02-23 16:39 UTC, hamikhambardzumyan approved these changes

2024-02-23 16:39 UTC, NarekArshakyan approved these changes

2024-02-23 16:40 UTC, merged